# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT
echo I am provisioning...
date > /etc/vagrant_provisioned_at
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: $script
  config.vm.box = "jasonc/centos7-32bit"
  config.vm.box_url = "https://app.vagrantup.com/jasonc/boxes/centos7-32bit"
  config.vm.host_name = "deployapp32"
  config.vm.provider :virtualbox do |vb|
    vb.name = "omnidb_centos_deployapp32"
  end
  config.vm.synced_folder ".", "/mnt/bootstrap"
  config.vm.provision :shell, :path => "bootstrap.sh"
end
