# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT
echo I am provisioning...
date > /etc/vagrant_provisioned_at
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: $script
  config.vm.box = "debian/stretch64"
  config.vm.box_url = "https://app.vagrantup.com/debian/boxes/stretch64"
  config.vm.host_name = "omnidbbdr1"
  config.vm.provider :virtualbox do |vb|
    vb.name = "omnidb_bdr_node1"
  end
  config.vm.network "private_network", ip: '192.168.56.103', :name => 'vboxnet0', :adapter => 2
  config.vm.network "forwarded_port", guest: 5432, host: 5403
  config.vm.synced_folder ".", "/mnt/bootstrap"
  config.vm.provision :shell, :path => "bootstrap.sh"
end
