# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT
echo I am provisioning...
date > /etc/vagrant_provisioned_at
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: $script
  config.vm.box = "bento/centos-6.10-i386"
  config.vm.box_url = "https://app.vagrantup.com/bento/boxes/centos-6.10-i386"
  config.vm.host_name = "deployserver32"
  config.vm.provider :virtualbox do |vb|
    vb.name = "omnidb_centos6_deployserver32"
  end
  config.vm.provision :shell, :path => "bootstrap.sh"
end
