import os

OMNIDB_VERSION = 'OmniDB 2.16.0'
OMNIDB_SHORT_VERSION = '2.16.0'
OMNIDB_ADDRESS = '127.0.0.1'
OMNIDB_WEBSOCKET_PORT = 25482
DEV_MODE = False
DESKTOP_MODE = False
HOME_DIR = None
APP_TOKEN = None
PWD_TIMEOUT_TOTAL = 1800
THREAD_POOL_MAX_WORKERS = 2
PATH = ''
