Vagrant.configure("2") do |config|
  #config.vbguest.auto_update = false
  config.vm.define "node1" do |node1|
    node1.vm.box = "debian/stretch64"
    node1.vm.hostname = 'node1'
    node1.vm.network :private_network, ip: '10.33.2.114'
    node1.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--name", "omnidb_pg10_node1"]
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    end
  end
  config.vm.define "node2" do |node2|
    node2.vm.box = "debian/stretch64"
    node2.vm.hostname = 'node2'
    node2.vm.network :private_network, ip: '10.33.2.115'
    node2.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--name", "omnidb_pg10_node2"]
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    end
  end
  config.vm.provision :shell, :path => "bootstrap.sh"
end
