# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT
echo I am provisioning...
date > /etc/vagrant_provisioned_at
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: $script
  config.vm.box = "centos/6"
  config.vm.box_url = "https://app.vagrantup.com/centos/boxes/6"
  config.vm.host_name = "deployplugin64"
  config.vm.provider :virtualbox do |vb|
    vb.name = "omnidb_centos6_deployplugin64"
  end
  config.vm.provision :shell, :path => "bootstrap.sh"
end
