# Generated by Django 3.0.8 on 2020-10-26 16:13

from django.db import migrations, models

def populate_config(apps, schema_editor):
    Config = apps.get_model('OmniDB_app', 'Config')
    Config(mig_2_to_3_done=False).save()


class Migration(migrations.Migration):

    dependencies = [
        ('OmniDB_app', '0001_3_0_0'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mig_2_to_3_done', models.BooleanField(default=False)),
            ],
        ),
        migrations.RunPython(
            code=populate_config,
        )
    ]
