# Generated by Django 3.0.8 on 2020-09-29 01:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('OmniDB_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consolehistory',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
