# Generated by Django 3.0.8 on 2020-10-06 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OmniDB_app', '0003_shortcut_os'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
