# Generated by Django 2.2.7 on 2020-03-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OmniDB_app', '0003_auto_20200316_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='font_size',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='theme',
            field=models.CharField(default='light', max_length=50),
        ),
    ]
