# Generated by Django 2.2.7 on 2020-03-17 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OmniDB_app', '0004_auto_20200316_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='connection',
            name='alias',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='connection',
            name='conn_string',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='connection',
            name='database',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='connection',
            name='password',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='connection',
            name='port',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='connection',
            name='server',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='connection',
            name='ssh_key',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='connection',
            name='ssh_password',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='connection',
            name='ssh_port',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='connection',
            name='ssh_server',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='connection',
            name='ssh_user',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='connection',
            name='use_tunnel',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='connection',
            name='user',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='connection',
            name='technology',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='OmniDB_app.Technology'),
            preserve_default=False,
        ),
    ]
