# Generated by Django 2.2.7 on 2020-03-17 17:49

from django.db import migrations

def populate_technologies(apps, schema_editor):
    Technology = apps.get_model('OmniDB_app', 'Technology')
    Technology(name='postgresql').save()
    Technology(name='mysql').save()
    Technology(name='mariadb').save()
    Technology(name='oracle').save()
    Technology(name='terminal').save()


class Migration(migrations.Migration):

    dependencies = [
        ('OmniDB_app', '0005_auto_20200317_1314'),
    ]

    operations = [
        migrations.RunPython(populate_technologies),
    ]
