# Generated by Django 2.2.7 on 2020-05-13 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('OmniDB_app', '0010_queryhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryhistory',
            name='snippet',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='ConsoleHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snippet', models.TextField(default='')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OmniDB_app.Connection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
