# Generated by Django 2.2.7 on 2020-05-14 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OmniDB_app', '0012_snippetfile_snippetfolder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippetfile',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='OmniDB_app.SnippetFolder'),
        ),
        migrations.AlterField(
            model_name='snippetfolder',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='OmniDB_app.SnippetFolder'),
        ),
    ]
