# Generated by Django 2.2.7 on 2020-05-14 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('OmniDB_app', '0013_auto_20200514_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shortcut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200)),
                ('ctrl_pressed', models.BooleanField(default=False)),
                ('shift_pressed', models.BooleanField(default=False)),
                ('alt_pressed', models.BooleanField(default=False)),
                ('meta_pressed', models.BooleanField(default=False)),
                ('key', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
