# Generated by Django 2.2.7 on 2020-05-14 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.contrib.auth.models import User
from django.utils import timezone

def populate_admin_user(apps,schema_editor):
    User.objects.create_user(username='admin',
                             password='admin',
                             email='',
                             last_login=timezone.now(),
                             is_superuser=True,
                             first_name='',
                             last_name='',
                             is_staff=False,
                             is_active=True,
                             date_joined=timezone.now())

def populate_shortcuts(apps, schema_editor):
    Shortcut = apps.get_model('OmniDB_app', 'Shortcut')
    shortcut_object = Shortcut(
        user=None,
        code='shortcut_run_query',
        ctrl_pressed=False,
        shift_pressed=False,
        alt_pressed=False,
        meta_pressed=True,
        key='Q'
    )
    shortcut_object.save()
    shortcut_object = Shortcut(
        user=None,
        code='shortcut_analyze',
        ctrl_pressed=False,
        shift_pressed=False,
        alt_pressed=False,
        meta_pressed=True,
        key='S'
    )
    shortcut_object.save()
    shortcut_object = Shortcut(
        user=None,
        code='shortcut_explain',
        ctrl_pressed=False,
        shift_pressed=False,
        alt_pressed=False,
        meta_pressed=True,
        key='A'
    )
    shortcut_object.save()
    shortcut_object = Shortcut(
        user=None,
        code='shortcut_indent',
        ctrl_pressed=False,
        shift_pressed=False,
        alt_pressed=False,
        meta_pressed=True,
        key='D'
    )
    shortcut_object.save()
    shortcut_object = Shortcut(
        user=None,
        code='shortcut_cancel_query',
        ctrl_pressed=False,
        shift_pressed=False,
        alt_pressed=False,
        meta_pressed=True,
        key='C'
    )
    shortcut_object.save()
    shortcut_object = Shortcut(
        user=None,
        code='shortcut_autocomplete',
        ctrl_pressed=False,
        shift_pressed=False,
        alt_pressed=False,
        meta_pressed=True,
        key='SPACE'
    )
    shortcut_object.save()
    shortcut_object = Shortcut(
        user=None,
        code='shortcut_left_inner_tab',
        ctrl_pressed=False,
        shift_pressed=False,
        alt_pressed=False,
        meta_pressed=True,
        key='O'
    )
    shortcut_object.save()
    shortcut_object = Shortcut(
        user=None,
        code='shortcut_right_inner_tab',
        ctrl_pressed=False,
        shift_pressed=False,
        alt_pressed=False,
        meta_pressed=True,
        key='P'
    )
    shortcut_object.save()
    shortcut_object = Shortcut(
        user=None,
        code='shortcut_new_inner_tab',
        ctrl_pressed=False,
        shift_pressed=False,
        alt_pressed=False,
        meta_pressed=True,
        key='I'
    )
    shortcut_object.save()
    shortcut_object = Shortcut(
        user=None,
        code='shortcut_remove_inner_tab',
        ctrl_pressed=False,
        shift_pressed=False,
        alt_pressed=False,
        meta_pressed=True,
        key='U'
    )
    shortcut_object.save()
    shortcut_object = Shortcut(
        user=None,
        code='shortcut_left_outer_tab',
        ctrl_pressed=False,
        shift_pressed=False,
        alt_pressed=False,
        meta_pressed=True,
        key='K'
    )
    shortcut_object.save()
    shortcut_object = Shortcut(
        user=None,
        code='shortcut_right_outer_tab',
        ctrl_pressed=False,
        shift_pressed=False,
        alt_pressed=False,
        meta_pressed=True,
        key='L'
    )
    shortcut_object.save()
    shortcut_object = Shortcut(
        user=None,
        code='shortcut_new_outer_tab',
        ctrl_pressed=False,
        shift_pressed=False,
        alt_pressed=False,
        meta_pressed=True,
        key='J'
    )
    shortcut_object.save()
    shortcut_object = Shortcut(
        user=None,
        code='shortcut_remove_outer_tab',
        ctrl_pressed=False,
        shift_pressed=False,
        alt_pressed=False,
        meta_pressed=True,
        key='H'
    )
    shortcut_object.save()
    shortcut_object = Shortcut(
        user=None,
        code='shortcut_next_console_command',
        ctrl_pressed=False,
        shift_pressed=False,
        alt_pressed=False,
        meta_pressed=True,
        key='M'
    )
    shortcut_object.save()
    shortcut_object = Shortcut(
        user=None,
        code='shortcut_previous_console_command',
        ctrl_pressed=False,
        shift_pressed=False,
        alt_pressed=False,
        meta_pressed=True,
        key='N'
    )
    shortcut_object.save()

class Migration(migrations.Migration):

    dependencies = [
        ('OmniDB_app', '0014_shortcut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortcut',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(populate_shortcuts),
        migrations.RunPython(populate_admin_user),
    ]
