# Generated by Django 2.2.7 on 2020-05-14 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OmniDB_app', '0015_auto_20200514_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortcut',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
