# Generated by Django 3.0.8 on 2020-07-21 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('OmniDB_app', '0016_auto_20200514_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonUnits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_chart', models.TextField(default='')),
                ('script_data', models.TextField(default='')),
                ('type', models.TextField(default='')),
                ('title', models.TextField(default='')),
                ('is_default', models.BooleanField(default=False)),
                ('interval', models.IntegerField(default=60)),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OmniDB_app.Technology')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MonUnitsConnections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.IntegerField(default=60)),
                ('plugin_name', models.TextField(default='')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OmniDB_app.Connection')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='OmniDB_app.MonUnits')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
