# Generated by Django 3.0.8 on 2020-07-21 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OmniDB_app', '0019_auto_20200721_1816'),
    ]

    operations = [
    ]
